Recipes/Recipes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('recipes/', include('recipesapp.urls', namespace='recipesapp')),
    path('about/', include('about.urls', namespace='about'))
]

Recipes/about/urls.py
from django.urls import path

from . import views


# Пространство имён.
app_name = 'about'

urlpatterns: list = [
    path('', views.get_about, name='get_about'),
]

Recipes/recipesapp/urls.py
from django.urls import path

from . import views


# Пространство имён.
app_name = 'recipesapp'

urlpatterns = [
    path('', views.get_recipes, name="get_recipes"),
    path('recipe/<int:recipe_id>/', views.current_recipe, name='current_recipe'),
]

Recipes/recipesapp/models.py
from django.db import models

# Create your models here.

Recipes/recipesapp/views.py
from django.shortcuts import render, HttpResponse

recipes = [
    {
        'id': 0,
        'name': 'Сырники',
        'ingridients': '''
            1) 2 упаковки творога;
            2) Щепотка соли;
            3) 5 столовых ложек сахара;
            4) 2 штуки куриных яиц;
            5) 2-3 столовые ложки муки;
            6) Растительное масло.''',
        'method': '''
            1) Берёшь 2 упаковки творога и разминаешь его в миске;
            2) Добавляешь щепотку соли и 5 столовых ложек сахара, перемешиваешь и оставляешь на 5 минут, чтобы разошёлся сахар;
            3) Добавляешь 2 яйца, перемешай;
            4) Добавляешь 2–3 столовые ложки муки. Тесто не должно быть слишком густым; оставляй ещё на 5–10 минут (мука должна немного разойтись);
            5) Жарим сырники на растительном масле на слабом огне (2–3 мощность);
            6) Сначала разогреваем сковороду вместе с маслом на максимальной мощности, затем убавляем и жарим сырники. Иначе они сгорят :)
            Желаю тебе вкуснейших сырников! ❤️''',
        'description': 'Традиционные сырники, мягкие и ароматные, идеально подходят для завтрака или десерта.'
    },
    {
        'id': 1,
        'name': 'Запеканка',
        'ingridients': '''
            1) 3 пачки творога;
            2) 0,5 чайной ложки соли;
            3) 7 столовых ложек сахара;
            4) 3 штуки куриных яиц;
            5) 3 столовые ложки манной крупы;
            6) Сливочное масло.''',
        'method': '''
            1) Берёшь 3 пачки творога, размельчаешь его;
            2) Солишь весь творог (0,5 ч.л.);
            3) Добавляешь 7 столовых ложек сахара, немного даёшь постоять;
            4) Добавляешь 3 штуки яиц, перемешиваешь;
            5) Добавляешь 5 столовых ложек манной крупы;
            6) Смазываешь форму растительным / сливочным маслом;
            7) Ставишь в разогретую до 180 градусов духовку на 40 - 50 минут;
            8) Подаём со сметанкой :)
            Самой вкусной запеканки тебе!❤️''',
        'description': 'Нежная творожная запеканка с манкой — отличный выбор для семейного обеда или ужина.'
    },
    {
        'id': 2,
        'name': 'Мясо по-капитански',
        'ingridients': '''
            1) Говяжья вырезка ~~ 500-600 грамм;
            2) Соль, перец, растительное масло;
            3) Лук, 1 шт.;
            4) Картошка ~~ 500 грамм;
            5) Майонез;
            6) Тёртый сыр.''',
        'method': '''
            1) Взять вырезку, нарезать стейками шириной около 1 см., отбить молоточком;
            2) Посолить, поперчить и добавить немного растительного масла;
            3) Выложить мясо в форму, сверху засыпать нарезанными: а) Лук; б) Картошку, нарезанную круглишками;
            4) В кружку (~~0,5 л.) выдавить немного майонеза, залить тёплой водой, перемешиваем;
            5) Заливаем форму с мясом, луком и картошкой содержимым кружки;
            6) Поставить в духовку, разогретую до 180 градусов, на 50 минут;
            7) По истечении 50 минут, пробуем картошку, если она готова - посыпаем тёртым сыром, и ставим еще на 10 минут;
            8) Вынимаем, когда сыр покроется золотистой, аппетитнейшей корочкой!
            Всё готово! Приятного аппетита!❤️''',
        'description': 'Сытное мясо с картошкой и ароматным сыром, запечённое в духовке под соусом — идеально для обеда.'
    },
    {
        'id': 3,
        'name': 'Борщ',
        'ingridients': '''
            1) Косточка (например, лопатка) для бульона;
            2) Соль, перец;
            3) Лук, 1 шт.;
            4) Свёкла;
            5) Капуста;
            6) Столовая ложка томатной пасты;
            7) Сахар (1 чайная ложка);
            8) Картошка;
            9) Морковь;
            10) Укроп.''',
        'method': '''
            1) Залить водой косточку (например лопатку) и дать постоять минут 40. Вода должна быть тёплой;
            2) Воду вылить, промыть косточку и залить чистой водой, немного посолить и поставить на плиту;
            3) Перед тем как закипит, снимаем всю пену.
            4) Когда закипит: кладём лук (мелконарезанный) и оставляем вариться полтора часа (90 мин.) на слабом огне;
            5) Добавить порезанную свёклу, варим ещё 10 минут;
            6) Вытаскиваем косточку, засыпаем капустой и выливаем столовую ложку томатной пасты, засыпаем сахар (1 ч.л.);
            7) Оставляем вариться на слабом огне ещё 10 минут;
            8) Выкладываем оставшееся: а) Картошку; б) Тёртую морковь. Варим до готовности;
            9) Затем разделываем косточку (выбираем мясо с косточки), режем укроп, добавляем всё в кастрюлю.
            10) Солим и перчим.
            Всё готово! Самого вкусного и наваристого борща тебе!❤️''',
        'description': 'Классический борщ с мясом, свёклой и капустой — насыщенный и ароматный суп, идеален для зимних обедов.'
    },
    {
        'id': 4,
        'name': 'Тефтельки',
        'ingridients': '''
            1) Фарш;
            2) Рис;
            3) Соль, перец;
            4) Томатная паста 1 столовая ложка;
            5) Майонез 1 столовая ложка;
            6) Морковь;
            7) Укроп;''',
        'method': '''
            1) Берём фарш и добавляем в него немного недоваренного риса, перемешиваешь;
            2) Добавляешь соль, перец по вкусу;
            3) Формируем некие шарики (Тефтельки);
            4) В кастрюлю наливаешь кипячённую воду и кладёшь туда 1 ст.л. томатной и пасты и 1 ст.л. майонеза;
            5) Солим воду по вкусу;
            6) Закидываешь туда тефтели и ставишь на огонь, чтобы закипело. 
            7) Пусть всё кипит минут 30-40 на медленном огне;
            8) Примерно за минут 20 до окончания кидаешь в кастрюлю тёртую морковь и порезанный укроп
            Всё готово! Приятнейших тефтелек тебе!❤️''',
        'description': 'Маленькие мясные шарики с рисом, томатным соусом и майонезом — идеальное домашнее блюдо.'
    },
    {
        'id': 5,
        'name': 'Домашняя пицца',
        'ingridients': '''
            1) 500 грамм муки;
            2) 7 грамм сухих дрожжей;
            3) 320 мл. тёплой воды;
            4) Соль;
            5) Манная крупа (совсем немного);
            6) Оливковое масло;
            7) 2-3 ложки резаных томатов в собственном соку;
            8) 50 грамм моцареллы;
            9) Хамон / ветчина / и другое;
            10) Тёртый твёрдый сыр (или любой другой).''',
        'method': '''
            1) Для приготовления теста нам понадобится: а) Мука; б) Дрожжи; в) Тёплая вода; г) Соль.
            2) Замешиваем все вышеперечисленное и делим на 3 части;
            3) Выкладываем тесто шариками подальше друг от друга, накрываем полотенцем, оставляем в тепле на 2 часа;
            4) Дальше раскатываем тесто, сбрызгиваем его оливковым маслом, размазываем по форме;
            5) Выкладываем на тесто 2-4 столовые ложки резаных томатов в собственном соку (или томатную пасту);
            6) Художественно разбрасываем кусочками 50 грамм моцареллы;
            7) Также разбрасываем хамон / ветчину;
            8) Посыпаем сверху сыром;
            9) Кладём в духовку на 230 градусов примерно на 5-7 минут.
            10) Периодически посматриваем, чтобы поймать момент, когда всё идеально готово.
            Всё готово! Самой вкусной пиццы тебе!❤️''',
        'description': 'Тонкое тесто с ароматными томатами, моцареллой и ветчиной — идеальная домашняя пицца!'
    },
    {
        'id': 6,
        'name': 'Солянка',
        'ingridients': '''
            1) Капуста (пол-качана);
            2) Растительное масло, сливочное масло;
            3) Мясо - вырезка;
            4) Картошка;
            5) Томатная паста, соль, перец;
            6) Морковь;
            7) Укроп.''',
        'method': '''
            1) Режешь мелко капусту, примерно половину качана, обжариваешь на растительном масле;
            2) Обжаренную капусту перекладываем в кастрюльку;
            3) Потом на этой же сковороде обжариваешь мясо - свежую вырезку;
            4) Обжаренное мясо также перекладываешь в кастрюльку к капусте;
            5) Чистишь и режешь кубиками картошку и закидываешь в кастрюльку - к капусте с мясом;
            6) В кастрюлю добавляешь кипячённую воду (чтобы почти покрывало картошку);
            7) Добавляешь томатную пасту, солишь, перчешь, оставляешь кипеть на медленном огне 40 минут;
            8) Когда обжариваешь капусту и мясо, в моменте можешь посолить;
            9) За минут 20 до окончания добавляешь тёртую морковь, а за 10 минут укроп;
            10) В конце добавляешь кусочек сливочного масла.
            Всё готово! Нежнейшей солянки тебе!❤️''',
        'description': 'Сытный суп с капустой, мясом и картошкой, заправленный томатной пастой и укропом.'
    },
    {
        'id': 7,
        'name': 'Макароны по-флотски',
        'ingridients': '''
            1) Лук;
            2) Морковь;
            3) Чеснок;
            4) Томатная паста;
            5) Фарш;
            6) Соль, перец;
            7) Макароны ракушки;
            8) Сливочное масло.''',
        'method': '''
            1) Обжариваешь лук, тёртую морковку и чесночёк;
            2) Добавляешь примерно 1 чайную ложку томатной пасты;
            3) Добавляешь фарш, обжариваешь, солишь, перчишь;
            4) В сковородку с фаршем кладёшь слегка недоваренные макароны (ракушки);
            5) Всё перемешиваешь, ещё немного обжариваешь;
            6) В конце добавляешь кусочек сливочного масла.
            Всё готово! Самых вкусных макарошек!❤️''',
        'description': 'Простое и вкусное блюдо с макаронами, фаршем и овощами, с добавлением томатной пасты.'
    },
    {
        'id': 8,
        'name': 'Блины',
        'ingridients': '''
            1) 3 яйца;
            2) Соль;
            3) Мука;
            4) Молоко;
            5) 5 столовых ложек сахара;''',
        'method': '''
            1) В миску добавляешь 3 яйца, немного солишь, взбиваешь вилкой;

Recipes/templates/recipesapp/get_recipes.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Рецепты. Полный список 
{% endblock %}

{% block content %}
  <h1>Рецепты</h1>
  <hr>                        
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
    {% for rp in recipes %}
      <div class="col">
        <div class="card" style="width: 100%;">
          {% if rp.id == 0 %}
            <img src="{% static 'img/sirniki.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 1 %}
            <img src="{% static 'img/zapekanka.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 2 %}
            <img src="{% static 'img/meat.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 3 %}
            <img src="{% static 'img/borsh.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 4 %}
            <img src="{% static 'img/tefteli.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 5 %}
            <img src="{% static 'img/pizza.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 6 %}
            <img src="{% static 'img/solyanka.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 7 %}
            <img src="{% static 'img/macarones.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 8 %}
            <img src="{% static 'img/blini.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 9 %}
            <img src="{% static 'img/chicken.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 10 %}
            <img src="{% static 'img/oladushki.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 11 %}
            <img src="{% static 'img/apple.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 12 %}
            <img src="{% static 'img/pirozhki.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 13 %}
            <img src="{% static 'img/chicken_soup.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 14 %}
            <img src="{% static 'img/kotleti.jpg' %}" class="card-img-top" width="200" height="300">
          {% elif rp.id == 15 %}
            <img src="{% static 'img/salad.jpg' %}" class="card-img-top" width="200" height="300">
          {% endif %}
          <div class="card-body">
            <h3 class="card-title">{{ rp.name }}</h3>
            <p class="card-text"><b>Описание:</b> {{ rp.description|truncatewords:8 }}.</p>
            <a href="{% url 'recipesapp:current_recipe' rp.id %}" class="btn btn-primary">Полный рецепт</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <style>
    .card {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s, box-shadow 0.2s;
    }
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }
    .btn-primary {
        transition: background-color 0.3s, transform 0.3s;
    }
    .btn-primary:hover {
        background-color: #0056b3;
        transform: scale(1.05);
    }
    .card-title {
        font-size: 1.5rem;
        font-weight: bold;
        margin-bottom: 10px;
    }
    .card-text {
        font-size: 1rem;
        color: #555;
    }
  </style>
{% endblock %}

Recipes/templates/recipesapp/recipe_card.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Рецепт: {{ recipe.name }}
{% endblock %}

{% block content %} 
  <style>
    .card {
        border: 1px solid #ccc;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        background-color: #f9f9f9;
        margin: 20px auto;
        max-width: 800px;
        border-radius: 10px;
        overflow: hidden;
    }
    .card img {
        width: 100%;
        height: 300px;
        object-fit: cover; /* Сохраняет пропорции, обрезая изображение по необходимости */
    }
    .card-title {
        font-size: 1.5rem;
        color: #333;
    }
    .card-body {
        padding: 20px;
    }
    .small {
        color: #777;
    }
    p {
        line-height: 1.6;
    }
  </style> 

  <div class="card mb-3">
    {% if recipe.id == 0 %}
      <img src="{% static 'img/sirniki.jpg' %}" class="card-img-top">
    {% elif recipe.id == 1 %}
      <img src="{% static 'img/zapekanka.jpg' %}" class="card-img-top">
    {% elif recipe.id == 2 %}
      <img src="{% static 'img/meat.jpg' %}" class="card-img-top">
    {% elif recipe.id == 3 %}
      <img src="{% static 'img/borsh.jpg' %}" class="card-img-top">
    {% elif recipe.id == 4 %}
      <img src="{% static 'img/tefteli.jpg' %}" class="card-img-top">
    {% elif recipe.id == 5 %}
      <img src="{% static 'img/pizza.jpg' %}" class="card-img-top">
    {% elif recipe.id == 6 %}
      <img src="{% static 'img/solyanka.jpg' %}" class="card-img-top">
    {% elif recipe.id == 7 %}
      <img src="{% static 'img/macarones.jpg' %}" class="card-img-top">
    {% elif recipe.id == 8 %}
      <img src="{% static 'img/blini.jpg' %}" class="card-img-top">
    {% elif recipe.id == 9 %}
      <img src="{% static 'img/chicken.jpg' %}" class="card-img-top">
    {% elif recipe.id == 10 %}
      <img src="{% static 'img/oladushki.jpg' %}" class="card-img-top">
    {% elif recipe.id == 11 %}
      <img src="{% static 'img/apple.jpg' %}" class="card-img-top">
    {% elif recipe.id == 12 %}
      <img src="{% static 'img/pirozhki.jpg' %}" class="card-img-top">
    {% elif recipe.id == 13 %}
      <img src="{% static 'img/chicken_soup.jpg' %}" class="card-img-top">
    {% elif recipe.id == 14 %}
      <img src="{% static 'img/kotleti.jpg' %}" class="card-img-top">
    {% elif recipe.id == 15 %}
      <img src="{% static 'img/salad.jpg' %}" class="card-img-top">
    {% endif %}
    <div class="card-body">
        <h1 class="card-title">{{ recipe.name }}</h1>
        <h3>Ингредиенты:</h3>
        <p class="card-text">{{ recipe.ingridients }}</p>
        <h2>Метод приготовления:</h2>
        <p class="card-text">{{ recipe.method }}</p>
    </div>  
  </div>
{% endblock %}